### ISSUE TITLE
Optional Tuples

### ISSUE THREAD

**Issue by ismailmustafa** [Gabriel439/Haskell-Optional-Args-Library#2]
So I have a type synonym I'd like to make optional like so:

```
type Color = (Word8, Word8, Word8)

data Params = Params { color :: Optional Color }
```

This compiles properly. However, when I actually set it to a value:

```
let settings = Params { color = (0,0,255) }
```

I get the following compilation error:

```
Couldn't match expected type ‘Optional Color’
                with actual type ‘(Integer, Integer, Integer)’
    In the ‘color’ field of a record
    In the expression: Params {color = (0, 0, 255)}
    In an equation for ‘params’: params = Params {color = (0, 0, 255)}
```

This error goes away when I change it to the following:

```
let settings = Params { color = Specific (0,0,255) }
```

However this defeats the purpose of this library.

How would I go about supporting tuples?

**Comment by Gabriella439** [comment]
Unfortunately, `ghc` does not let libraries overload tuple syntax so this is not possible.  You will have to wrap the tuple in `Specific` or `pure`

**Comment by ismailmustafa** [comment]
Ah I see, thank you.

**Comment by Gabriella439** [comment]
You're welcome!
