### ISSUE TITLE
[Question] No enough benefit whenever IsString needs to be concatenated ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Optional-Args-Library#4]
I feel the `optional-args` library fails flat because whenever I goes from : 

`"hello"` to `"hello" <> name` (which in real code is pretty much inevitable) . The `isString` trick won't apply because the variable of type `Text` will determine the whole expression to be of type `Text` instead of `Optional Text`.

I then need to wrap the expression with "Specific" to obtain a `Optional Text`. At that point, the gain compared to `Maybe` is lost and I usually end up replacing `Optional` with `Maybe` to keep it simple (introducing something new has a cost even when the package is really tiny).

Am I missing something ?
Is there a way around that issue somehow  ?

**Comment by Gabriella439** [comment]
You can use `"hello" <> pure name` and still keep it general without having to import any `optional-args` modules

**Comment by PierreR** [comment]
Yes ! I didn't think about that. Thanks for the tip !
